db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: PostgreSQL@2
    MYSQL_DATABASE: sample
    # MYSQL_USER: user1
    # MYSQL_PASSWORD: PostgreSQL@2
  ports:
    - "3306"
  volumes:
   - ./db:/docker-entrypoint-initdb.d

web:
  image: devopsthink/loginwebpage:latest
  # Environment variables do not appear to be getting loaded the first time Tomcat starts!
  environment:
    JDBC_URL: jdbc:mysql://db:3306/sample?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    JDBC_USER: root
    JDBC_PASS: PostgreSQL@2
  ports:
   - "8080:8080"
  # volumes:
  # - ./tomcat/webapps:/usr/local/tomcat/webapps
  links:
    - db
